from django.core.management.base import BaseCommand

from core.models import Car, User


CAR_DATA = [
    {
        "brand": "Tesla",
        "model_name": "Model 3",
        "tagline": "Electric sedan with strong value and range",
        "year": 2025,
        "body_type": "Sedan",
        "fuel_type": "Electric",
        "transmission": "Single-speed automatic",
        "drive_type": "RWD",
        "price": 38990,
        "mileage": 132,
        "horsepower": 283,
        "torque": 420,
        "top_speed": 125,
        "zero_to_sixty": 5.8,
        "range_km": 438,
        "battery_capacity": 60,
        "seating_capacity": 5,
        "cargo_space": 22.9,
        "ground_clearance": 138,
        "safety_rating": 4.9,
        "warranty_years": 4,
        "image_url": "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1200&q=80",
        "description": "A clean-tech sedan built for buyers who want strong software, low running cost, and dependable range.",
        "key_features": "Autopilot,15-inch center display,Supercharger support,Glass roof,Over-the-air updates",
        "pros": "Excellent charging ecosystem\nStrong range for the price\nSimple and modern cabin",
        "cons": "Minimal physical buttons\nRide quality is firm on rough roads",
        "featured": True,
    },
    {
        "brand": "BMW",
        "model_name": "i4",
        "tagline": "Premium electric gran coupe with sporty feel",
        "year": 2025,
        "body_type": "Sedan",
        "fuel_type": "Electric",
        "transmission": "Single-speed automatic",
        "drive_type": "RWD",
        "price": 52200,
        "mileage": 118,
        "horsepower": 335,
        "torque": 430,
        "top_speed": 118,
        "zero_to_sixty": 5.5,
        "range_km": 412,
        "battery_capacity": 81,
        "seating_capacity": 5,
        "cargo_space": 10.0,
        "ground_clearance": 124,
        "safety_rating": 4.8,
        "warranty_years": 4,
        "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80",
        "description": "A refined electric BMW for buyers who want strong driving dynamics with premium comfort and finish.",
        "key_features": "Curved display,Premium interior,Fast charging,Driver assistance,Harman audio",
        "pros": "Refined handling\nUpscale cabin quality\nBalanced power delivery",
        "cons": "Higher starting price\nLess cargo room than some rivals",
        "featured": True,
    },
    {
        "brand": "Hyundai",
        "model_name": "Creta",
        "tagline": "Popular family SUV with balanced value",
        "year": 2025,
        "body_type": "SUV",
        "fuel_type": "Petrol",
        "transmission": "6-speed automatic",
        "drive_type": "FWD",
        "price": 21000,
        "mileage": 34,
        "horsepower": 157,
        "torque": 192,
        "top_speed": 121,
        "zero_to_sixty": 10.2,
        "range_km": 650,
        "battery_capacity": 50,
        "seating_capacity": 5,
        "cargo_space": 15.3,
        "ground_clearance": 190,
        "safety_rating": 4.4,
        "warranty_years": 3,
        "image_url": "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80",
        "description": "A practical SUV with approachable pricing, good features, and family-friendly proportions.",
        "key_features": "Panoramic sunroof,10.25-inch infotainment,360 camera,Connected car tech,Ventilated seats",
        "pros": "Comfortable city SUV\nGood feature list\nEasy ownership experience",
        "cons": "Not the quickest in class\nCabin plastics vary by trim",
        "featured": True,
    },
    {
        "brand": "Kia",
        "model_name": "Seltos",
        "tagline": "Sharp-looking SUV with strong features",
        "year": 2025,
        "body_type": "SUV",
        "fuel_type": "Petrol",
        "transmission": "CVT automatic",
        "drive_type": "FWD",
        "price": 22500,
        "mileage": 33,
        "horsepower": 160,
        "torque": 195,
        "top_speed": 119,
        "zero_to_sixty": 9.8,
        "range_km": 630,
        "battery_capacity": 50,
        "seating_capacity": 5,
        "cargo_space": 15.9,
        "ground_clearance": 190,
        "safety_rating": 4.5,
        "warranty_years": 3,
        "image_url": "https://images.unsplash.com/photo-1494905998402-395d579af36f?auto=format&fit=crop&w=1200&q=80",
        "description": "A stylish SUV with strong tech and a youthful personality for buyers wanting a feature-rich package.",
        "key_features": "Dual-screen dashboard,Bose audio,ADAS suite,Wireless charging,Connected navigation",
        "pros": "Stylish exterior design\nGood infotainment setup\nUseful ADAS features",
        "cons": "Ride can feel firm\nTop trims get expensive",
        "featured": True,
    },
    {
        "brand": "Mercedes-Benz",
        "model_name": "C-Class",
        "tagline": "Luxury sedan with comfort-first character",
        "year": 2025,
        "body_type": "Sedan",
        "fuel_type": "Petrol",
        "transmission": "9-speed automatic",
        "drive_type": "RWD",
        "price": 44850,
        "mileage": 30,
        "horsepower": 255,
        "torque": 400,
        "top_speed": 130,
        "zero_to_sixty": 6.0,
        "range_km": 720,
        "battery_capacity": 66,
        "seating_capacity": 5,
        "cargo_space": 12.6,
        "ground_clearance": 135,
        "safety_rating": 4.9,
        "warranty_years": 4,
        "image_url": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
        "description": "A premium sedan focused on elegant comfort, high-end materials, and long-distance refinement.",
        "key_features": "Portrait infotainment display,Burmester audio,Ambient lighting,MBUX assistant,Driver package",
        "pros": "Excellent cabin ambience\nSmooth daily driving\nStrong safety package",
        "cons": "Rear seat is not class-leading\nOptions can raise price quickly",
        "featured": True,
    },
    {
        "brand": "Audi",
        "model_name": "Q7",
        "tagline": "Three-row luxury SUV with solid all-round ability",
        "year": 2025,
        "body_type": "SUV",
        "fuel_type": "Diesel",
        "transmission": "8-speed automatic",
        "drive_type": "AWD",
        "price": 59200,
        "mileage": 25,
        "horsepower": 335,
        "torque": 500,
        "top_speed": 130,
        "zero_to_sixty": 5.9,
        "range_km": 820,
        "battery_capacity": 85,
        "seating_capacity": 7,
        "cargo_space": 35.7,
        "ground_clearance": 178,
        "safety_rating": 4.9,
        "warranty_years": 4,
        "image_url": "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=1200&q=80",
        "description": "A premium SUV for families who need space, confident highway performance, and luxury-grade comfort.",
        "key_features": "Quattro AWD,Air suspension,Virtual cockpit,Seven seats,Matrix LED headlamps",
        "pros": "Spacious and premium\nStrong highway stability\nPractical third row",
        "cons": "Expensive to maintain\nLarge footprint in cities",
        "featured": True,
    },
    {
        "brand": "Porsche",
        "model_name": "Taycan",
        "tagline": "Performance EV with serious driver appeal",
        "year": 2025,
        "body_type": "Sedan",
        "fuel_type": "Electric",
        "transmission": "2-speed automatic",
        "drive_type": "AWD",
        "price": 90900,
        "mileage": 96,
        "horsepower": 522,
        "torque": 640,
        "top_speed": 143,
        "zero_to_sixty": 4.5,
        "range_km": 396,
        "battery_capacity": 93,
        "seating_capacity": 4,
        "cargo_space": 14.3,
        "ground_clearance": 127,
        "safety_rating": 4.8,
        "warranty_years": 4,
        "image_url": "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1200&q=80",
        "description": "An enthusiast-focused electric sedan with sharp acceleration, high-speed confidence, and premium fit and finish.",
        "key_features": "Launch control,800V charging,Digital cockpit,Adaptive air suspension,Sport Chrono pack",
        "pros": "Exciting acceleration\nExcellent steering feel\nFast charging architecture",
        "cons": "High purchase cost\nRear packaging is tighter",
        "featured": True,
    },
    {
        "brand": "Toyota",
        "model_name": "Highlander",
        "tagline": "Efficient hybrid SUV built for families",
        "year": 2025,
        "body_type": "SUV",
        "fuel_type": "Hybrid",
        "transmission": "eCVT automatic",
        "drive_type": "AWD",
        "price": 36620,
        "mileage": 36,
        "horsepower": 243,
        "torque": 270,
        "top_speed": 112,
        "zero_to_sixty": 7.9,
        "range_km": 940,
        "battery_capacity": 65,
        "seating_capacity": 7,
        "cargo_space": 16.0,
        "ground_clearance": 203,
        "safety_rating": 4.9,
        "warranty_years": 5,
        "image_url": "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80",
        "description": "A dependable family SUV that focuses on efficiency, comfort, and long-term ownership confidence.",
        "key_features": "Hybrid powertrain,Toyota Safety Sense,Three-row seating,Wireless CarPlay,Adaptive cruise",
        "pros": "Excellent efficiency for size\nStrong reliability reputation\nComfortable family package",
        "cons": "Not very sporty\nThird row best for short trips",
        "featured": False,
    },
    {
        "brand": "BMW",
        "model_name": "X5 xDrive40i",
        "tagline": "Performance luxury SUV with flexible cabin",
        "year": 2025,
        "body_type": "SUV",
        "fuel_type": "Petrol",
        "transmission": "8-speed automatic",
        "drive_type": "AWD",
        "price": 65200,
        "mileage": 23,
        "horsepower": 375,
        "torque": 520,
        "top_speed": 130,
        "zero_to_sixty": 5.3,
        "range_km": 760,
        "battery_capacity": 83,
        "seating_capacity": 5,
        "cargo_space": 33.9,
        "ground_clearance": 214,
        "safety_rating": 4.8,
        "warranty_years": 4,
        "image_url": "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80",
        "description": "A powerful luxury SUV with excellent cabin quality, strong road manners, and easy daily usability.",
        "key_features": "xDrive AWD,Curved display,Panoramic roof,Adaptive suspension,Parking assistant",
        "pros": "Strong engine response\nPremium interior quality\nConfident all-weather traction",
        "cons": "Options can be costly\nRide is firm on large wheels",
        "featured": False,
    },
    {
        "brand": "Honda",
        "model_name": "City e:HEV",
        "tagline": "Efficient hybrid sedan with sensible ownership",
        "year": 2025,
        "body_type": "Sedan",
        "fuel_type": "Hybrid",
        "transmission": "eCVT automatic",
        "drive_type": "FWD",
        "price": 24000,
        "mileage": 45,
        "horsepower": 126,
        "torque": 253,
        "top_speed": 108,
        "zero_to_sixty": 10.5,
        "range_km": 880,
        "battery_capacity": 40,
        "seating_capacity": 5,
        "cargo_space": 14.8,
        "ground_clearance": 165,
        "safety_rating": 4.6,
        "warranty_years": 3,
        "image_url": "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1200&q=80",
        "description": "A practical sedan for buyers who want excellent fuel economy, low running costs, and proven comfort.",
        "key_features": "Hybrid system,Lane watch camera,ADAS suite,LED lighting,Automatic climate control",
        "pros": "Very efficient\nSmooth urban drive\nEasy to live with",
        "cons": "Performance is modest\nRear styling is conservative",
        "featured": False,
    },
]


class Command(BaseCommand):
    help = "Seed the database with demo car data for CarVault."

    def handle(self, *args, **options):
        seller_one, _ = User.objects.get_or_create(
            email="seller1@carvault.test",
            defaults={
                "firstname": "Aarav",
                "lastname": "Motors",
                "role": User.Role.SELLER,
                "account_state": User.AccountState.ACTIVE,
                "is_active": True,
            },
        )
        seller_one.set_password("Seller123!")
        seller_one.save()

        seller_two, _ = User.objects.get_or_create(
            email="seller2@carvault.test",
            defaults={
                "firstname": "Mira",
                "lastname": "Garage",
                "role": User.Role.SELLER,
                "account_state": User.AccountState.ACTIVE,
                "is_active": True,
            },
        )
        seller_two.set_password("Seller123!")
        seller_two.save()

        buyer_user, _ = User.objects.get_or_create(
            email="buyer@carvault.test",
            defaults={
                "firstname": "Test",
                "lastname": "Buyer",
                "role": User.Role.BUYER,
                "account_state": User.AccountState.ACTIVE,
                "is_active": True,
            },
        )
        buyer_user.set_password("Buyer123!")
        buyer_user.save()

        created_count = 0
        updated_count = 0

        for index, car_data in enumerate(CAR_DATA):
            seller = seller_one if index % 2 == 0 else seller_two
            defaults = {
                **car_data,
                "seller": seller,
                "listing_status": Car.ListingStatus.ACTIVE,
            }
            _, created = Car.objects.update_or_create(
                brand=car_data["brand"],
                model_name=car_data["model_name"],
                defaults=defaults,
            )
            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Car seed complete. Created {created_count} cars and updated {updated_count} cars."
            )
        )
