# Generated by Django 6.0.2 on 2026-03-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("tagline", models.CharField(max_length=160)),
                ("year", models.PositiveIntegerField(default=2025)),
                (
                    "body_type",
                    models.CharField(
                        choices=[
                            ("SUV", "SUV"),
                            ("Sedan", "Sedan"),
                            ("Hatchback", "Hatchback"),
                            ("Coupe", "Coupe"),
                            ("Pickup", "Pickup"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("Petrol", "Petrol"),
                            ("Diesel", "Diesel"),
                            ("Electric", "Electric"),
                            ("Hybrid", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transmission", models.CharField(max_length=50)),
                ("drive_type", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        help_text="Mileage in MPG or equivalent"
                    ),
                ),
                ("horsepower", models.PositiveIntegerField()),
                ("torque", models.PositiveIntegerField(help_text="Torque in Nm")),
                (
                    "top_speed",
                    models.PositiveIntegerField(help_text="Top speed in mph"),
                ),
                (
                    "zero_to_sixty",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="0-60 mph time in seconds",
                        max_digits=4,
                    ),
                ),
                ("range_km", models.PositiveIntegerField(help_text="Range in km")),
                (
                    "battery_capacity",
                    models.PositiveIntegerField(
                        help_text="Battery/fuel system capacity figure"
                    ),
                ),
                ("seating_capacity", models.PositiveIntegerField(default=5)),
                (
                    "cargo_space",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Cargo space in cubic feet",
                        max_digits=5,
                    ),
                ),
                (
                    "ground_clearance",
                    models.PositiveIntegerField(help_text="Ground clearance in mm"),
                ),
                ("safety_rating", models.DecimalField(decimal_places=1, max_digits=2)),
                ("warranty_years", models.PositiveIntegerField(default=3)),
                ("image_url", models.URLField()),
                ("description", models.TextField()),
                (
                    "key_features",
                    models.TextField(help_text="Comma-separated features"),
                ),
                ("pros", models.TextField(help_text="One point per line")),
                ("cons", models.TextField(help_text="One point per line")),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["brand", "model_name"],
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "male"), ("female", "female"), ("other", "other")],
                default="male",
                max_length=100,
            ),
        ),
    ]
