# Generated by Django 6.0.2 on 2026-03-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_car_listing_status_car_seller_user_account_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="image_file",
            field=models.FileField(blank=True, null=True, upload_to="cars/"),
        ),
        migrations.AlterField(
            model_name="car",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
